apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
  labels:
    app: podinfo
spec:
  minReadySeconds: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
      labels:
        app: podinfo
        scheduler: fargate
    spec:
      containers:
      - image: 181637548333.dkr.ecr.us-west-1.amazonaws.com/aws-ecr-kubetwittersample:1.0.0
        imagePullPolicy: Always
        name: podinfod
        ports:
        - containerPort: 5000
          protocol: TCP
#      containers:
#        - image: 181637548333.dkr.ecr.us-west-1.amazonaws.com/aws-ecr-kubetwittersample:1.0.0
#          imagePullPolicy: Always
#          name: podinfod
#          ports:
#          - name: http
#            containerPort: 5000
#            protocol: TCP
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
#        livenessProbe:
#          exec:
#            command:
#            - podcli
#            - check
#            - http
#            - localhost:5000/metrics
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
#        readinessProbe:
#          exec:
#            command:
#            - podcli
#            - check
#            - http
#            - localhost:5000/metrics
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
