apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-service-monitor
  labels:
    app: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  endpoints:
  - port: 5000